/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

 const awsmobile = {
     "aws_project_region": "ap-southeast-2",
     "aws_cognito_identity_pool_id": "ap-southeast-2:9a85229d-ec5e-4d19-85f2-88ddbff55c12",
     "aws_cognito_region": "ap-southeast-2",
     "aws_user_pools_id": "ap-southeast-2_IECJrfsBS",
     "aws_user_pools_web_client_id": "70tukoi6g0s2aqav09tlkv8f0j",
     "oauth": {}
 };


export default awsmobile;
